FROM ubuntu:latest

RUN apt update
RUN apt install openjdk-11-jdk -y
RUN apt install wget -y
RUN apt install unzip -y
RUN apt install tar -y

RUN wget -P /opt/ https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.72/bin/apache-tomcat-9.0.72.tar.gz
RUN tar -zvxf /opt/apache-tomcat-9.0.72.tar.gz

WORKDIR /opt/apache-tomcat-9.0.72
#RUN chmod -R 777 /opt/apache-tomcat-9.0.72
#RUN ls /
#RUN echo '<role rolename="manager-gui"/>' >> /opt/apache-tomcat-9.0.72/conf/tomcat-users.xml
#RUN echo '<user username="tomcat" password="tomcat" roles="manager-gui"/>' >> /opt/apache-tomcat-9.0.72/conf/tomcat-users.xml

#RUN sed -i '21i\<!--' /opt/apache-tomcat-9.0.72/webapps/manager/META-INF/context.xml
#RUN sed -i '24i\-->' /opt/apache-tomcat-9.0.72/webapps/manager/META-INF/context.xmli

ENV PATH="/opt/apache-tomcat-9.0.72/bin:${PATH}"

EXPOSE 8080

CMD ["/opt/apache-tomcat-9.0.72.tar.gz/bin/startup.sh","run"]
